ci:
  skip: ['golangci-lint', 'go-test']

repos:
  - repo: local
    hooks:
      - id: go-test
        name: Go Test
        language: system
        entry: go
        args: ['test', '-v', '-skip-rootful-tests']
        pass_filenames: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: check-yaml
        args: [-m]
        exclude: ^test/e2e/testdata|^vendor
      - id: check-json
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.59.1
    hooks:
      - id: golangci-lint
        entry: golangci-lint run --fix
        args:
          - "--modules-download-mode=vendor"
          - "--timeout=20m"
        types: [go]
        language: golang
        require_serial: true
        pass_filenames: false
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args: [
          "--ignore-words-list",
          "afterall",
          "--check-filenames",
          "--check-hidden",
          "-S",
          "test/e2e/testdata/*,go.sum,go.mod",
        ]
        pass_filenames: true
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.5.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
